"use client";

import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

type ExportToPDFProps = {
  targetId: string;
  filename: string;
  title?: string;
};

/**
 * A button that exports a specific DOM element to PDF using the browser's print dialog.
 * Uses a clean print stylesheet for professional output.
 */
export function ExportToPDF({ targetId, filename, title }: ExportToPDFProps) {
  const handleExport = () => {
    const element = document.getElementById(targetId);
    if (!element) return;

    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const content = element.innerHTML;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${filename}</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
            
            * { margin: 0; padding: 0; box-sizing: border-box; }
            
            body {
              font-family: 'Inter', -apple-system, sans-serif;
              color: #1e1b4b;
              padding: 40px;
              line-height: 1.6;
              -webkit-print-color-adjust: exact;
              print-color-adjust: exact;
            }

            /* Header */
            .pdf-header {
              display: flex;
              align-items: center;
              justify-content: space-between;
              border-bottom: 2px solid #6366f1;
              padding-bottom: 16px;
              margin-bottom: 24px;
            }
            .pdf-header h1 {
              font-size: 24px;
              font-weight: 800;
              color: #6366f1;
            }
            .pdf-header .date {
              font-size: 12px;
              color: #64748b;
            }
            .pdf-header .brand {
              font-size: 11px;
              color: #94a3b8;
              letter-spacing: 0.1em;
              text-transform: uppercase;
            }

            /* Content overrides */
            table { width: 100%; border-collapse: collapse; margin: 12px 0; }
            th { background: #f1f5f9; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; padding: 10px 12px; text-align: left; }
            td { padding: 10px 12px; border-bottom: 1px solid #f1f5f9; font-size: 13px; }
            tr:nth-child(even) { background: #fafafa; }

            h2, h3 { margin: 16px 0 8px; color: #1e1b4b; }
            h2 { font-size: 18px; font-weight: 700; }
            h3 { font-size: 14px; font-weight: 600; }

            .stat { display: inline-block; padding: 8px 16px; margin: 4px; border-radius: 8px; background: #f8fafc; border: 1px solid #e2e8f0; }
            .stat-label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; color: #94a3b8; font-weight: 600; }
            .stat-value { font-size: 20px; font-weight: 800; color: #1e1b4b; }

            /* Hide interactive elements */
            button, input, select, textarea, .no-print { display: none !important; }

            .pdf-footer {
              margin-top: 40px;
              padding-top: 16px;
              border-top: 1px solid #e2e8f0;
              font-size: 10px;
              color: #94a3b8;
              display: flex;
              justify-content: space-between;
            }

            @media print {
              body { padding: 20px; }
              @page { margin: 15mm; }
            }
          </style>
        </head>
        <body>
          <div class="pdf-header">
            <div>
              <h1>${title || filename}</h1>
              <div class="brand">StudentSync — AI-Powered Student Platform</div>
            </div>
            <div class="date">${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
          </div>
          
          ${content}
          
          <div class="pdf-footer">
            <span>Generated by StudentSync</span>
            <span>${new Date().toLocaleString('en-IN')}</span>
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();

    // Wait for fonts to load then print
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 500);
  };

  return (
    <Button variant="outline" size="sm" onClick={handleExport}
      className="rounded-lg hover:bg-indigo-50 hover:border-indigo-200 hover:text-indigo-600 transition-all gap-1.5">
      <Download className="w-3.5 h-3.5" />
      Export PDF
    </Button>
  );
}
